default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ocpihub_development
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>

test:
  <<: *default
  database: ocpihub_test
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>

staging:
  <<: *default
  database: ocpihub_staging
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>

production:
  <<: *default
  database: ocpihub_production
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>
