default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: ocpihub_development
    username: reyzapermanasaputra
    password: 1234567890
    host: localhost
    port: 5432
  logs_db:
    <<: *default
    database: ocpihub_development
    username: reyzapermanasaputra
    password: 1234567890
    host: localhost
    port: 5432

staging:
  primary:
    <<: *default
    database: jomcharge_hub_db
    username: jomcharge
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_DB_HOST'] %>
  logs_db:
    <<: *default
    database: jomcharge_hub_logs_db
    username: jomcharge
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_DB_HOST'] %>
